### ISSUE TITLE
What are Spider Barge, Spill Barge, and Idler Barge? (and their differences)

### ISSUE THREAD

**Issue by gojanpaolo** [gldd-se/PostDredge-Public#18]
Based from an email from Dane, we could categorize the cutter job types as
- Beach
- Spill Barge
- Spider Barge
- Chopping

But what are spill barge and spider barge? also, what is idler barge?

**Comment by gojanpaolo** [comment]
> Spider Barges: Spider barges are used to load barges with material that is pumped by a cutter suction dredge. There are currently three spider barges in the GLDD fleet
https://www.gldd.com/gldd-equipment-auxiliary/

**Comment by gojanpaolo** [comment]
> An idler barge is a barge that is usually of a similar width to a matching dredge.
One end of this barge is pinned to the aft end of the dredge at the spud wells. The aft
end of the idler barge then has its own set of spud wells, spuds, winches, and spud
controls. Instead of a 200’ long dredge swinging an arc based on its 200’ long length,
the addition of a 100’ idler barge allows the dredge to swing a digging arc based on a 300’ radius. Even with the usual 90° arc of swing this allows more efficient dredging in
a wide channel. 
http://www.portlite.com/blog/wp-content/uploads/2014/06/ID-and-Appraisal-of-Marine-Dredging-Equipment.pdf

It looks like job type (and spill barge and spider barge) are independent from idler barge

**Comment by rcriii42** [comment]
Correct.

Idler barge connects to the dredge to lengthen it, and sometimes provide a spider carriage.

Spider barge is at the discharge end to load scores. It is so-named because of the loading arms.

Spill barge is also at the  discharge  end, used when placing material in open water.


Robert Ramsdell
Director of Production Engineering and R&D
Great Lakes Dredge & Dock Company
Rcramsdell@gldd.com



-------- Original message --------
